{application,ad_1,
             [{description,"An OTP application"},
              {vsn,"0.1.0"},
              {registered,[]},
              {mod,{ad_1_app,[]}},
              {applications,[kernel,stdlib]},
              {env,[]},
              {modules,[ad_1,ad_1_app,ad_1_sup]},
              {licenses,["Apache-2.0"]},
              {links,[]}]}.
